github:
    clientId: ENC[AES256_GCM,data:D4wo3kfACUNE7VoxZEbBA9GeUSg=,iv:JMJv7dPFuHaSx07bB/VuhjiUSL1B2i4WxwDLsXPbMT4=,tag:tYh+x4irId9rcapfYoZlfw==,type:str]
    clientSecret: ENC[AES256_GCM,data:wXO51fTYf90VIVLYaSVWd+EaGu4mGMCRMLKVywndn9UbDClHM/GR1w==,iv:Jv5+1dtR7s/8jKPX0CVN2zhUK/zGUfC1h9F9qdE2ejg=,tag:w55x/8yCfr7R9ElopVM+aQ==,type:str]
oauth2Proxy:
    cookieSecret: ENC[AES256_GCM,data:jZCfeLJCdyCTK5gfrsYsin+GSxObcxkgJt4HT5IDo1VfHYhHfu9C0aD6FjA=,iv:cnkPw+KPq8yFSSxFetkaPgXGlTPvBEr3k26py58XGd4=,tag:3oeIgkA32GNHLKwWYHPNnQ==,type:str]
sops:
    age:
        - recipient: age1zxzu3s39vx9zufj8enwuv67tw7svlcf50lxm42yjllhh3awprf2sw65ps8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1U0xJK0FLcGdLTzEwT2xK
            aUFhakN1dmltUFNiR0FJcFJ0VWZscGFNN2tzCktoT3V0dnVnZmdFMWtZVTQzVkdm
            bk83K2IzeWtHb2JieVVnSmRYRXJvQk0KLS0tIFlnMzY2S1NZOCtab1AybEFRMmli
            dmNUVENiQWhrRzg2aUpSYS9wZ0MrdncKSajuE7nEpjRlJAM4BmUGxLZgwUBoU04H
            r2OF4Rg7fKb8ZwV26Uix4GUEbbWQS622EsXOcmSlR+puZv0f50OYxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:52:55Z"
    mac: ENC[AES256_GCM,data:VWTembgijjwKcutL3p4MKCwVhlKS5pGCb//K0Q8PoQqr7fl+N0fRNr7R8xE3XkwPigE8/7Ighf0NOa8gSvVjgQBhwmtCe5SXm1OPpYcavGHTuCJRWOCzW/Rv93ZQQT2+q/Nl+A4zcOgXJYHJGXAWLep9CnL7TO+jpi8Qhuslr9s=,iv:czcLMrtl5ikQmSBpy6FL/TlPneeTn46XkgqyIovp2OY=,tag:DCuVCc9lDmKHMO7yuC+66g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
