github:
    clientId: ENC[AES256_GCM,data:D4wo3kfACUNE7VoxZEbBA9GeUSg=,iv:JMJv7dPFuHaSx07bB/VuhjiUSL1B2i4WxwDLsXPbMT4=,tag:tYh+x4irId9rcapfYoZlfw==,type:str]
    clientSecret: ENC[AES256_GCM,data:wXO51fTYf90VIVLYaSVWd+EaGu4mGMCRMLKVywndn9UbDClHM/GR1w==,iv:Jv5+1dtR7s/8jKPX0CVN2zhUK/zGUfC1h9F9qdE2ejg=,tag:w55x/8yCfr7R9ElopVM+aQ==,type:str]
oauth2Proxy:
    cookieSecret: ENC[AES256_GCM,data:mUMU+eRbRI4U5Y7+qiFgSSyPBr7r73n44zyCxjodNC4yJwdggHVFnJzimls=,iv:FGL45UV7v0Pn5yPshvZBICZyzy9nSUUvptIasJuxGt8=,tag:hoFybm4anJY+11E0ZTPLKw==,type:str]
sops:
    age:
        - recipient: age1zxzu3s39vx9zufj8enwuv67tw7svlcf50lxm42yjllhh3awprf2sw65ps8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1U0xJK0FLcGdLTzEwT2xK
            aUFhakN1dmltUFNiR0FJcFJ0VWZscGFNN2tzCktoT3V0dnVnZmdFMWtZVTQzVkdm
            bk83K2IzeWtHb2JieVVnSmRYRXJvQk0KLS0tIFlnMzY2S1NZOCtab1AybEFRMmli
            dmNUVENiQWhrRzg2aUpSYS9wZ0MrdncKSajuE7nEpjRlJAM4BmUGxLZgwUBoU04H
            r2OF4Rg7fKb8ZwV26Uix4GUEbbWQS622EsXOcmSlR+puZv0f50OYxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:57:26Z"
    mac: ENC[AES256_GCM,data:mNMlHUaXkxlBQM7GAwP4gm29AHTEGJPHYo5V+jw5ZDFsyY/GEHzTpKy/JwpbdhYi1D3UH1jyWrua+d/HwJxZTT7oG3Ixqby6LRPf+601ytUTDVQgvVZOkbG1mStv8HA0z/uKzToBJmAEpz+ziVRHBsKJQL+0yKa3r8dcs0b6lfo=,iv:CN5VQ+s1Aornq6U84CpP/Xt6CDjLCwBWxxcfnww5Spo=,tag:rj8oLflFhmNcLpwZQ4gH/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
