github:
  # Fill these with your GitHub OAuth App credentials.
  clientId: "your-client-id"
  clientSecret: "your-client-secret"

oauth2Proxy:
  # Optional if set by deploy script, but included for documentation.
  cookieSecret: "replace-with-32-byte-base64-secret"
  emailDomain: "*"
  cookieSecure: false
