{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "game-2048.fullname" . }}
  labels:
    {{- include "game-2048.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ $.Values.ingress.frontend.path }}
            pathType: {{ default "Prefix" $.Values.ingress.frontend.pathType }}
            backend:
              service:
                name: {{ include "game-2048.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
          {{- if $.Values.ingress.backend.enabled }}
          - path: {{ $.Values.ingress.backend.path }}
            pathType: {{ default "Prefix" $.Values.ingress.backend.pathType }}
            backend:
              service:
                name: {{ include "game-2048.fullname" $ }}-backend
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
