{{- if and .Values.oauth2Proxy.enabled (not .Values.oauth2Proxy.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "game-2048.fullname" . }}-oauth2-proxy
  labels:
    {{- include "game-2048.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
type: Opaque
data:
  {{- if .Values.oauth2Proxy.clientID }}
  {{ .Values.oauth2Proxy.secretKeys.clientIDKey }}: {{ .Values.oauth2Proxy.clientID | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth2Proxy.clientSecret }}
  {{ .Values.oauth2Proxy.secretKeys.clientSecretKey }}: {{ .Values.oauth2Proxy.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth2Proxy.cookieSecret }}
  {{ .Values.oauth2Proxy.secretKeys.cookieSecretKey }}: {{ .Values.oauth2Proxy.cookieSecret | b64enc | quote }}
  {{- end }}
{{- end }}
