apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oauth2-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oauth2-proxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "oauth2-proxy.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --provider=github
            - --http-address=0.0.0.0:4180
            - --upstream=static://202
            - --email-domain={{ .Values.oauth2Proxy.emailDomain }}
            - --redirect-url=http://{{ .Values.ingress.host }}/oauth2/callback
            - --cookie-secure={{ .Values.oauth2Proxy.cookieSecure | ternary "true" "false" }}
            - --set-xauthrequest=true
            - --reverse-proxy=true
            - --scope=read:user
          envFrom:
            - secretRef:
                name: {{ include "oauth2-proxy.fullname" . }}
          ports:
            - name: http
              containerPort: 4180
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
