apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: {{ required "github.clientId is required" .Values.github.clientId | quote }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ required "github.clientSecret is required" .Values.github.clientSecret | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ required "oauth2Proxy.cookieSecret is required" .Values.oauth2Proxy.cookieSecret | quote }}
