apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/RompfRobert/datavisyn-devops-challenge.git
    targetRevision: dev
    path: helm/backend
    helm:
      values: |
        replicaCount: 2
        service:
          internalTrafficPolicy: Local
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values: ["backend"]
                    - key: app.kubernetes.io/instance
                      operator: In
                      values: ["backend"]
                topologyKey: kubernetes.io/hostname
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.demo.svc.cluster.local:4180/oauth2/auth
            nginx.ingress.kubernetes.io/auth-signin: https://challenge.rompf.dev/oauth2/start?rd=$escaped_request_uri
          hosts:
            - host: challenge.rompf.dev
              paths:
                - path: /api
                  pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
