apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048
  namespace: argocd
  labels:
    app.kubernetes.io/name: game-2048
    app.kubernetes.io/instance: game
spec:
  project: default
  source:
    repoURL: https://github.com/RompfRobert/datavisyn-devops-challenge
    targetRevision: master
    path: helm/game-2048
    helm:
      releaseName: dev
      values: |
        ingress:
          enabled: true
          className: nginx
          hosts: []
        oauth2Proxy:
          enabled: true
          cookieSecure: false
          existingSecret: oauth2-proxy-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allow-empty: false
    syncOptions:
      - RespectIgnoreDifferences=true
