apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/RompfRobert/datavisyn-devops-challenge.git
    targetRevision: dev
    path: helm/oauth2-proxy
    helm:
      valueFiles:
        - secrets://secrets/values.sops.yaml
      values: |
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-dns
          host: challenge.rompf.dev
          path: /oauth2
          pathType: Prefix
          tls:
            - secretName: challenge-rompf-dev-tls
              hosts:
                - challenge.rompf.dev
        secret:
          create: true
        oauth2Proxy:
          emailDomain: "*"
          cookieSecure: true
          redirectScheme: https
          scope: "user"
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
