replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: public.ecr.aws/l6m2t8p7/docker-2048
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
